### ISSUE TITLE
bundle list not correct

### ISSUE THREAD

**Issue by RandomClaim** [clearfraction/distribution#10]
Hello,

on a fresh install of clearlinux, adding the the repo with the command in the Readme does not seem to work correctly.
After adding the repo, this is the output fro querying the available bundles:

```bash
sudo swupd 3rd-party bundle-list -a
_____________________________________
 3rd-Party Repository: clearfraction
_____________________________________

All available bundles:
 - brave
 - codecs
 - fluffychat
 - foliate
 - os-core
 - secrets
 - shotwell
 - vscodium

Total: 8
```

The packages listed are different from the ones in https://github.com/clearfraction/bundles/tree/master/configs. For once [sway-extras](https://github.com/clearfraction/bundles/blob/master/configs/sway-extras) and [alacritty](https://github.com/clearfraction/bundles/blob/master/configs/alacritty) are missing. Instead there is "os-core", I'm not sure what that is.

**Comment by paulcarroty** [comment]
Hi, your list is correct. `Sway-extras` and `alacritty` bundles aren't available yet, new release planned for early April. 
You can extract the packages from CI artifacts and help to test them.

**Comment by RandomClaim** [comment]
Oh okay, sorry about that then. Thank you for your work
