### ISSUE TITLE
Couldn't add the 3rd party repo

### ISSUE THREAD

**Issue by ChunHou20c** [clearfraction/distribution#11]
curl  -download failed: response (503) 'https://clearfraction.herokuapp.com/update/version/format30/latest'
![image](https://user-images.githubusercontent.com/93393878/165868769-3fa4a850-5863-4275-b73f-19b027b359ae.png)

**Comment by paulcarroty** [comment]
Huh, we're off the Heroku monthly limits. Will figure it out.

**Comment by paulcarroty** [comment]
Fixed.

**Comment by ChunHou20c** [comment]
Thanks
