### ISSUE TITLE
FFmpeg CUDA support

### ISSUE THREAD

**Issue by paulcarroty** [clearfraction/distribution#14]
⬇️

**Comment by marioroy** [comment]
I have a question. There is "Requires: %{name}-filemap" in the ffmpeg.spec file. Where is ffmpeg-filemap defined or is it external? Well, I created ffmpeg-cuda/ffmpeg-cuda.spec based on your recent 5.1 ffmpeg/ffmpeg.spec.

No write access at the moment.

**Comment by paulcarroty** [comment]
> no write access to ffmpeg-cuda.

Try again.

> Where is ffmpeg-filemap defined or is it external?

Fixed. This is for [clr-elf-replace](https://github.com/clearlinux-pkgs/clr-elf-replace), I tried to setup AVX2 builds but had not enough free time to finish it.

**Comment by marioroy** [comment]
> Fixed.
That worked.

**Comment by marioroy** [comment]
I'm not sure if workflows/build-core.yml ran for nv-codec-headers as the spec file was committed/pushed before .github/workflows. The ffmpeg-cuda spec file `BuildRequires: nv-codec-headers`.

**Comment by marioroy** [comment]
How does one install a 3rd-party bundle containing ffmpeg-cuda?

codecs: ffmpeg, ffmpeg-libs
codecs-cuda: ffmpeg-cuda, ffmpeg-cuda-libs

sudo swupd 3rd-party bundle-add codecs  (or)
sudo swupd 3rd-party bundle-add codecs-cuda

Are the ffmpeg-cuda-*rpm (packages) temporary? I do not know your plan :)

**Comment by marioroy** [comment]
Please feel free to disregard the following:

I wish to deprecate the [scripts](https://github.com/marioroy/nvidia-driver-on-clear-linux/tree/main/HWAccel) folder. Being able to install codecs-cuda will immensely elevate the experience for folks using NVIDIA graphics.

Completed: nv-codec-headers that provides `ffmpeg -hwaccel nvdec` capability. 

Remaining tasks:

1. libvdpau  (dependency for the VDPAU back-end VA-API driver)
2. vdpau-va-driver-vp9  (used by Chrome-like browsers for hardware acceleration)
3. vaapi-nvidia (NVDEC back-end VA driver used by Firefox, ffmpeg, mpv)

Simulation for folks using NVIDIA graphics.
```text
sudo swupd 3rd-party bundle-add codecs-cuda
```
Chrome
```text
export LIBVA_DRIVERS_PATH=/opt/3rd-party/lib64/dri  (or)
export LIBVA_DRIVERS_PATH=/opt/3rd-party/bundles/clearfraction/usr/lib64/dri
export LIBVA_DRIVER_NAME=vdpau
```
Firefox, ffmpeg -hwaccel vaapi, and mpv
```text
export LIBVA_DRIVERS_PATH=/opt/3rd-party/lib64/dri  (or)
export LIBVA_DRIVERS_PATH=/opt/3rd-party/bundles/clearfraction/usr/lib64/dri
export LIBVA_DRIVER_NAME=nvdec (or nvidia linked to nvdec)
```
FFmpeg
```text
ffmpeg -hwaccel vaapi -c:v {vp9, av1}
ffmpeg -hwaccel nvdec -c:v {vp9, vp9_cuvid, av1, av1_cuvid}
Since there is libbvdpau, I can add --enable-vdpau option to configure
ffmpeg -hwaccel vdpau -c:v {vp9, av1} 
```

**Comment by marioroy** [comment]
Plus somewhere in the Clear Fraction site or documentation area, a guide on how to configure the Firefox configuration file `~/.config/firefox.conf` so that mindful of Xorg and Wayland. Also mindful of Intel Graphics, NVIDIA graphics, etc.

Ditto for Brave and Chrome-like browsers. See the `brave` and `firefox` folders in [HWAccel](https://github.com/marioroy/nvidia-driver-on-clear-linux/tree/main/HWAccel).

That's all! Again, please feel free to disregard all of this.

**Comment by marioroy** [comment]
Info: The next FFmpeg release 5.2 will default to running on the GPU if the capability exist in hardware. Currently, decoding AV1 defaults to `-c:v libdav1d` when omitting the `-c:v` option.

See FFmpeg commits [df5defe](https://github.com/FFmpeg/FFmpeg/commit/df5defe15a29dfca5f13224eb5da821095f6c745) and [ad67ea9](https://github.com/FFmpeg/FFmpeg/commit/ad67ea9eeed2cc8edab8662b7503ce4a49247b1d).

**Comment by marioroy** [comment]
If helpful and when the time comes, I can have the [install-driver](https://github.com/marioroy/nvidia-driver-on-clear-linux) script create symbolic links for:
```text
 /usr/lib64/dri/{nvdec,nvidia,vdpau}_drv_video.so
```
to:
```text
 /opt/3rd-party/bundles/clearfraction/usr/lib64/dri/{nvdec,nvidia,vdpau}_*
```

Folks will then not need to configure LIBVA_DRIVERS_PATH. For swupd safety, the `pre-install-driver` script creates /etc/swupd/config.
```text
/usr/lib64/dri/(nvdec|nvidia|vdpau)_drv_video\.so
```

**Comment by paulcarroty** [comment]
Ohhh.

> How does one install a 3rd-party bundle containing ffmpeg-cuda?

All bundles are defined [here](https://github.com/clearfraction/bundles/tree/master/configs).

> Are the ffmpeg-cuda-*rpm (packages) temporary

Yes, [mass-rebuild](https://github.com/clearfraction/mass-rebuild/actions) cares about releases; GitHub artifacts will be wiped after 90 days.

Environment variables are defined in `/distibution/README.md`, `/docs` required. I'll create the repos^ above if you wanna maintain them and add minimal docs for the scripts.

**Comment by marioroy** [comment]
I completed testing the SPEC file `libvdpau.spec` for libvdpau. The libvdpau package is a dependency for building the VDPAU back-end VA-API driver which is next on my list. In the meantime, I tested VDPAU capability in FFmpeg by updating the ffmpeg-cuda.spec file locally. libvdpau 1.5 works great.

```text
Requires:       libvdpau
BuildRequires:  libvdpau-dev

configure --enable-vdpau
```

Note: The next FFmpeg 5.2 release will default to `-c:v av1` automatically on capable GPUs. Currently, AV1 renders via libdav1d if omitting the `-c:v av1` option.
```text
ffmpeg -hwaccel vdpau -c:v vp9 -i input_vp9.webm -f null -  # GPU
ffmpeg -hwaccel vdpau -c:v av1 -i input_av1.mp4 -f null -   # GPU
```

From [FFmpeg HWAccelIntro](https://trac.ffmpeg.org/wiki/HWAccelIntro), "Several decoders are currently supported through VDPAU in libavcodec, in particular H.264, MPEG-1/2/4, and VC-1, AV1."

See also https://www.phoronix.com/news/NVIDIA-AV1-VDPAU-FFmpeg

**Comment by paulcarroty** [comment]
Check invite to `libvdpau`.

**Comment by marioroy** [comment]
> inserted task-list

Thank you! Pushed libvdpau.spec.

**Comment by marioroy** [comment]
> All bundles are defined [here](https://github.com/clearfraction/bundles/tree/master/configs).

Should I see `ffmpeg-cuda` in the list? I will remove 3rd-party and try again.
```bash
$ sudo swupd 3rd-party update
$ sudo swupd 3rd-party bundle-list -a
_____________________________________
 3rd-Party Repository: clearfraction
_____________________________________

All available bundles:
 - alacritty
 - brave
 - btop
 - codecs
 - fluffychat
 - foliate
 - imv
 - kitty
 - os-core
 - secrets
 - shotwell
 - sway-extras
 - vscodium
 - waybar

Total: 14
```

**Comment by paulcarroty** [comment]
> Should I see ffmpeg-cuda in the list?

After new release, not yet.

**Comment by marioroy** [comment]
I pushed a hot fix to add `%define abi_package %{nil}` in libvdpau.spec. But the build continues to fail. Is this due to stale *.abi files?
```text
error: Installed (but unpackaged) file(s) found:
[530](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:531)
   /usr/share/abi/libvdpau.so.1.abi
[531](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:532)
   /usr/share/abi/vdpau/libvdpau_trace.so.1.abi
[532](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:533)
    Downloading https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/1.5/libvdpau-1.5.tar.bz2 to /home/libvdpau-1.5.tar.bz2
[533](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:534)
    Installed (but unpackaged) file(s) found:
[534](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:535)
   /usr/share/abi/libvdpau.so.1.abi
[535](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:536)
   /usr/share/abi/vdpau/libvdpau_trace.so.1.abi
[536](https://github.com/clearfraction/libvdpau/runs/7775980932?check_suite_focus=true#step:3:537)
Build failed
```

**Comment by marioroy** [comment]
I'm unable to reproduce the abi issue locally.
```text
Installed (but unpackaged) file(s) found
```

**Comment by marioroy** [comment]
I'm ignoring the abi issue for now so able to move forward. The libvdpau spec file seems fine and has all the proper build requires and requires.
```text
%define _unpackaged_files_terminate_build 0
```
```text
warning: Installed (but unpackaged) file(s) found:
   /usr/share/abi/libvdpau.so.1.abi
   /usr/share/abi/vdpau/libvdpau_trace.so.1.abi
```

**Comment by marioroy** [comment]
I completed mpv-cuda.

Thus far, the workflow isn't installing the build dependencies. I ensured the following exists in the mpv-cuda spec file.
```text
Requires: ffmpeg-cuda-libs
BuildRequires : nv-codec-headers
BuildRequires : ffmpeg-cuda-dev
```

Testing: The mpv binary utilizes the NVIDIA video engine while playing videos :)
```text
mpv --hwdec={nvdec,cuda}
mpv --hwdec defaults to nvdec

[vd] vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd] av1_cuvid (av1) - Nvidia CUVID AV1 decoder
```

**Comment by marioroy** [comment]
My bad... The repository name `vaapi-nvidia` was met to be `nvidia-vaapi-driver`. Can you rename it please. Blessings and grace.

**Comment by paulcarroty** [comment]
> I'm ignoring the abi issue for now so able to move forward. The libvdpau spec file seems fine and has all the proper build requires and requires.

```
%install
rm -rf %{buildroot}//usr/share/abi
```

> Thus far, the workflow isn't installing the build dependencies

https://github.com/clearfraction/ffmpeg-cuda/commit/9fbe1adcab430f25f635752c1e8675c1f73295fd

**Comment by marioroy** [comment]
Thanks. I will update libvdpau.spec.

For mpv-cuda it also needs ffmpeg-cuda (buildrequires ffmpeg-cuda-libs) in addition to nv-codec-headers. Or is ffmpeg-cuda sufficient and the workflow determines to pull in nv-codec-headers as well.

I'm new to GitHub workflows.

I finished nvidia-vaapi-driver, but will wait for the rename from vaapi-nvidia to nvidia-vaapi-driver.

**Comment by marioroy** [comment]
I reverted the change. libvdpau is failing. I have no idea on how to rid of the abi error: Installed (but unpackaged) file(s) found.

**Comment by marioroy** [comment]
mpv-cuda: It cannot find ffmpeg-cuda.

![image](https://user-images.githubusercontent.com/7031085/184076445-5fa643f5-86ca-425e-849a-20a4a97971b9.png)

**Comment by marioroy** [comment]
Putting back `%define _unpackaged_files_terminate_build 0` in libvdpau.spec so that I can complete the VDPAU back-end VA driver. The other NVDEC back-end VA driver completed workflow successfully.

**Comment by marioroy** [comment]
I finished vdpau-va-driver-vp9, but do not have write access.

**Comment by paulcarroty** [comment]
> mpv-cuda: It cannot find ffmpeg-cuda or something else.
> 
> ![image](https://user-images.githubusercontent.com/7031085/184076445-5fa643f5-86ca-425e-849a-20a4a97971b9.png)

'Cause wrong workflow, should be `build.yml`, `build-core.yml` for compilation with Clear dependencies only.

**Comment by marioroy** [comment]
Ah... 👍

**Comment by marioroy** [comment]
The `nv-codec-headers` entry is not needed inside the codecs-cuda bundle, but no problem if you want to keep it there.

I wondered myself and tested to be sure. The binaries FFmpeg, Mpv, and the NVDEC VA driver work without the headers, confirming nv-codec-headers lives in the `BuildRequires` world and not used otherwise.

**Comment by paulcarroty** [comment]
Fine, remove the headers.

**Comment by paulcarroty** [comment]
@marioroy https://github.com/clearfraction/bundles/runs/7821549270?check_suite_focus=true#step:4:232

**Comment by marioroy** [comment]
@paulcarroty I'm not sure that I understand what's going on. Do we need bundles and bundles-cuda? Because, the files in the ffmpeg-cuda package conflict with ffmpeg. Likewise, the files in the mpv-cuda package conflict with mpv.

If preferring not to have both bundles and bundles-cuda, another path is to have one ffmpeg and mpv supporting cuda. The dependency is simply nv-codec-headers. I can test the binaries on Intel without NVIDIA graphics.

Again, I'm not sure I understand the error.

**Comment by marioroy** [comment]
- [ ] Test ffmpeg and mpv binaries built with nv-codec-headers on an Intel box lacking NVIDIA graphics.

**Comment by marioroy** [comment]
The ffmpeg and mpv binaries built with nv-codec-headers work on an Intel box lacking NVIDIA graphics. Below is the intel_gpu_top screenshot while playing media using Mpv.
```bash
$ mpv --hwdec input_avc1.mp4
```

![image](https://user-images.githubusercontent.com/7031085/184512101-dfe64e03-1d7e-4d73-b7d3-6e24c539599f.png)

Next, is the intel_gpu_top screenshot while decoding the same avc1 media with FFmpeg.
```bash
$ ffmpeg -hwaccel vaapi -i input_avc1.mp4 -f null -
```

![image](https://user-images.githubusercontent.com/7031085/184512143-8cb23d29-3500-4a24-ad68-0326664c140f.png)

**Comment by marioroy** [comment]
I created a repository for testing yt-dlp and mpv. This is how I verified video hardware acceleration working with mpv. The great news is that we only need one set of binaries `ffmpeg` and `mpv` built with `nv-codec-headers`.

https://github.com/marioroy/youtube-play

**Comment by paulcarroty** [comment]
I'm against shipping cuda for all 'cause it will fix the case, but not the problem. Need to do a research how Clear handle cases like this with kernels, GCC, LLVM etc.

**Comment by paulcarroty** [comment]
They're renaming ELFs and library paths: https://github.com/clearlinux-pkgs/gcc11/blob/main/gcc11.spec#L284

Yeah, I know you don't like it 😀

Going to ship this release without CUDA and we'll figure it out later.

**Comment by paulcarroty** [comment]
Two ways: 
1) Play with buildsystems like above with flags `--program-suffix`
2) Tuning global paths like `/opt/3rd-party/bundles/clearfraction/cuda` together with $PATH & $LD. Seems easier.

**Comment by marioroy** [comment]
Great! Trying option 2.
```text
%define cuda_prefix /cuda
%define cuda_bindir /cuda/usr/bin
%define cuda_includedir /cuda/usr/include
%define cuda_libdir /cuda/usr/lib64
%define cuda_datadir /cuda/usr/share
```

**Comment by paulcarroty** [comment]
Hold on, only ffmpeg-cuda & mpv-cuda.

**Comment by marioroy** [comment]
Thanks. You answered my question. Option 2 { ffmpeg-cuda, mpv-cuda }

**Comment by paulcarroty** [comment]
Alternative path: `/user/local`, already in CF `environment.d` config, should work out the box.

**Comment by marioroy** [comment]
Great! Changing to `/usr/local`.
```text
%define cuda_prefix /usr/local
%define cuda_bindir /usr/local/bin
%define cuda_includedir /usr/local/include
%define cuda_libdir /usr/local/lib64
%define cuda_datadir /usr/local/share
```

**Comment by marioroy** [comment]
It appears that `rpmbuild` (internally) is changing /usr/local to /usr :(

**Comment by paulcarroty** [comment]
`%make_install PREFIX=/usr/local`

**Comment by marioroy** [comment]
`%make_install PREFIX=/usr/local` not working either. Wow!

https://stackoverflow.com/questions/72203988/rpm-macros-for-usr-local-prefix

> no Fedora package can contain files or directories or modify files under ... /usr/local as these directories are not permitted to be used by Distributions in the FHS

**Comment by marioroy** [comment]
> If this will be also ignored, we can use a hack on bundles generation stage.

Folks install either `codecs` or `codecs-cuda`. But not both -- so no files conflicts. Or in the event an existing codecs installation exist, must remove first before installing the other.

**Comment by marioroy** [comment]
Simulations if having separate bundles ffmpeg and ffmpeg-cuda.

1. Intel-based notebooks with integrated NVIDIA graphics.
2. Intel-based desktops with dedicated NVIDIA graphics.
3. Two separate installations ffmpeg and ffmpeg-cuda (different paths). Will user need to fiddle with environment variables? Which binary is used when typing `ffmpeg`, `mpv`?

I respect your decision to keep them separate. But, what a wonderful experience if one bundle (e.g. one path, no fiddling with env, no concerns installing or updating codecs), no worries if codecs exists that must be removed prior to installing the other or vice versa.

Yikes, IMHO.

`nv-codec-headers` is a build dependency and not in the final bundle. Thus, no difference between ffmpeg, ffmpeg-cuda and mpv, mpv-cuda with regards to the list of files. In the end, it is nvidia-vaapi-driver + vdpau-va-driver-vp9 and dependencies that are extra.

**Comment by marioroy** [comment]
`nv-codec-headers` is a build dependency and not in the final bundle. So no difference between ffmpeg, ffmpeg-cuda and mpv, mpv-cuda with regards to the list of files. The extra files are nvidia-vaapi-driver, vdpau-va-driver-vp9, and dependencies. Should these be placed in another bundle "libva-nvidia-drivers"?

**Comment by paulcarroty** [comment]
I vote for two bundles 'cause it's provide more control: we don't need to play with FFmpeg versions when CUDA will stop working, plus easy to drop and easy to pick it up. If you can't build ffmpeg&mpv with `/usr/local` profile, I hope to do it tomorrow.

> Intel-based notebooks with integrated NVIDIA graphics.

Optimus? This crap should die in fire.

> So no difference between ffmpeg, ffmpeg-cuda and mpv, mpv-cuda with regards to the list of files

ELFs are different, the file name and paths are the same.

> "libva-nvidia-drivers" or "nvidia-va-drivers"

All up to you.

**Comment by marioroy** [comment]
The `/usr/local` option is working :)

```text
%define cuda_prefix /usr/local-cuda
%define cuda_bindir /usr/local-cuda/bin
%define cuda_includedir /usr/local-cuda/include
%define cuda_libdir /usr/local-cuda/lib64
%define cuda_datadir /usr/local-cuda/share

%install (adding)
mv %{buildroot}%{cuda_prefix} %{buildroot}/usr/local
pushd %{buildroot}/usr
ln -s local local-cuda
popd

%files libs (adding)
/usr/local-cuda
```

The symbolic link `local-cuda` pointing to `local` is needed in the event Makefiles add -wl linker path flags.

**Comment by marioroy** [comment]
Setting LDFLAGS with `-Wl,-rpath` is working. This ensures the ffmpeg-cuda binaries and libraries search for the ffmpeg-cuda libs first, regardless of how LD_LIBRARY_PATH is set. :)

**Comment by marioroy** [comment]
I modified the LDFLAGS above ensuring simulations passing. Well, here it is.
```
export LDFLAGS="-Wl,-rpath=/usr/local-cuda/lib64,-rpath=/opt/3rd-party/bundles/clearfraction/usr/local-cuda/lib64,-rpath=/opt/3rd-party/bundles/clearfraction/usr/lib64"
```
Given Simulations:
1. User compiles FFmpeg from source and installs to /usr/local, libs residing in /usr/local/lib64. Does not affect the 3rd-party ffmepg-cuda.
2. User installs both 3rd-party codecs and 3rd-party codecs-cuda. Does not affect the 3rd-party ffmpeg-cuda. No problem.
3. The 3rd-party environment vars has /opt/3rd-party/.../usr/lib64 first before /opt/3rd-party/.../usr/local/lib64. Does not affect the 3rd-party ffmpeg and ffmpeg-cuda.
4. Myself building ffmpeg-cuda (/usr/local-cuda is a symbolic link to /usr/local) and searched first before /opt/3rd-party/...

PASS

**Comment by marioroy** [comment]
I'm finished testing and pushed the update for ffmpeg-cuda.  Currently, waiting for ffmpeg-cuda to complete workflow before pushing the update for mpv-cuda.

**Comment by marioroy** [comment]
The updates were pushed for ffmpeg-cuda and mpv-cuda. Each workflow completed successfully.

**Comment by marioroy** [comment]
"VDPAU on Radeon R300 and newer GPUs is supported by mesa-vdpau."
    -- Arch Linux [Wiki](https://wiki.archlinux.org/title/Hardware_video_acceleration)

The codecs-cuda bundle supports AMD (vaapi,vdpau), Intel (qsv,vaapi), and NVIDIA (cuda/nvdec,vaapi,vdpau).

```bash
sudo swupd 3rd-party bundle-install codecs-cuda
```

**Comment by marioroy** [comment]
The funny thing; is I have no use for FFmpeg at the moment. So, a lot of work for something I do not need. Look at the options passed to Mpv in the YouTube play scripts (URL above). Blessings and Grace.

Thank you, Clear Fraction, for making this possible.

**Comment by paulcarroty** [comment]
Great job! Parallel installation is the huge achievement.

Now wait a stable Clear release > 36820 and trigger mass-rebuild manually.
Two test CL releases *this weekend*, I wonder what happened.

**Comment by marioroy** [comment]
I installed both ffmpeg and ffmpeg-cuda. Next, I went through the simulations outlined above.

2. User installs both 3rd-party codecs and 3rd-party codecs-cuda. **Affects the 3rd-party codecs-cuda if LD_LIBRARY_PATH is set and /opt/3rd-party/.../usr/lib64 comes before /opt/3rd-party/.../usr/local-cuda/lib64.**

There are no file conflicts for installing both. However, the user must choose one or the other, but not install both. Interestingly, LD_LIBRARY_PATH has higher precedence, it seems, over -Wl,-rpath. Next, I tried `patchelf --set-rpath ...` too. LD_LIBRARY_PATH has higher precedence.

So not recommended to install both.

**Comment by marioroy** [comment]
Should I move codecs-cuda from experimental-configs to configs in bundles?

**Comment by paulcarroty** [comment]
> move codecs-cuda from experimental-configs to configs in bundles

Sure.

> Next, I tried patchelf --set-rpath ... ensuring local-cuda paths are set. Unfortunately, LD_LIBRARY_PATH has higher precedence.

Cool, that's something new to me. Maybe for completely independence you should remove local-cuda -> cuda.

**Comment by marioroy** [comment]
The symbolic link is needed `local-cuda -> local`. That was to overcome the rpmbuild issue. The binaries and libs expect local-cuda in the path.
```
$ ffmpeg -version
ffmpeg version 5.1-1ad802c Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12 (Clear Linux OS for Intel Architecture)
configuration: --disable-static --extra-ldflags=-ldl --prefix=/usr/local-cuda --bindir=/usr/local-cuda/bin --datadir=/usr/local-cuda/share/ffmpeg --incdir=/usr/local-cuda/include/ffmpeg --libdir=/usr/local-cuda/lib64 --shlibdir=/usr/local-cuda/lib64 --enable-rdft --enable-pixelutils --extra-ldflags=-ldl --enable-vaapi --enable-bzlib --enable-libdrm --enable-fontconfig --enable-gcrypt --enable-gmp --enable-version3 --enable-gnutls --enable-ladspa --enable-libass --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-opengl --enable-libopus --enable-libpulse --enable-libsnappy --enable-libspeex --enable-libvorbis --enable-libv4l2 --enable-sdl2 --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-avfilter --enable-swscale --enable-postproc --enable-pthreads --enable-librtmp --enable-libmfx --disable-static --enable-shared --enable-gpl --disable-debug --disable-doc --enable-libfdk-aac --enable-nonfree --enable-libdav1d --enable-vulkan --enable-libglslang --enable-libsvtav1 --enable-nvdec --enable-vdpau
```

**Comment by paulcarroty** [comment]
https://stackoverflow.com/questions/33519640/why-i-cannot-override-search-path-of-dynamic-libraries-with-ld-library-path

**Comment by marioroy** [comment]
Great, then one can have both installed.  Though it requires fiddling with env vars at the user level. How many folks are going to need both codecs and codecs-cuda?  If intel graphics only, install codecs. Else install codecs-cuda for AMD/NVIDIA graphics or Intel box with discrete AMD/NVIDIA.

**Comment by marioroy** [comment]
I tried `chrpath` as described in the article. LD_LIBRARY_PATH has higher precedence.

**Comment by paulcarroty** [comment]
So we need `LD_LIBRARY_PATH` without `/opt../usr/local` for double install and ffmpeg-cuda? Just add it to README and case closed.

**Comment by marioroy** [comment]
Also, unsetting LD_LIBRARY_PATH works for codecs-cuda. I will update the README.

**Comment by marioroy** [comment]
Which README file?

**Comment by paulcarroty** [comment]
https://github.com/clearfraction/distribution/blob/master/README.md

**Comment by marioroy** [comment]
The mass-rebuild workflow completed successfully. :) Moreover, updated the distribution README file.

![image](https://user-images.githubusercontent.com/7031085/184583840-bc949c81-859b-42b7-9427-c97b6081e144.png)

**Comment by paulcarroty** [comment]
Great.
The triggered [bundles build](https://github.com/clearfraction/bundles/actions/runs/2858721821) failed, 'cause release designed to be read-only. Wait for `>36820`.

**Comment by marioroy** [comment]
Interesting. Oh... You missed mentioning the great news :)  That is, no issues with codecs-cuda in the mixer workflow. What a relief :)
```text
Adding bundle "codecs" from local bundles
Adding bundle "codecs-cuda" from local bundles

=> BUILD BUNDLES
Resolving packages for codecs
Resolving files for codecs
Resolving packages for codecs-cuda
Resolving files for codecs-cuda

Installing all bundles to full chroot...
7/14 codecs
8/14 codecs-cuda

=> CREATE MANIFESTS
- codecs
- codecs-cuda
```

**Comment by paulcarroty** [comment]
Available in [36840](https://clearfraction.herokuapp.com/update/36840/).
