### ISSUE TITLE
Integrate yt-dlp into mpv

### ISSUE THREAD

**Issue by paulcarroty** [clearfraction/distribution#15]
https://github.com/marioroy/youtube-play, credit for @marioroy 

Target: September 2022.

**Comment by marioroy** [comment]
Yes, of course. Passing the URL and -F arguments (given to yt-dlp) obtains a list of available formats. I can be explicit and play AC01, VP9, or AV01 content (youtube-play url format). This is how I tested the various hardware acceleration methods.

**Comment by marioroy** [comment]
The main reason, originally, was for playing 10-bit (HDR) content. For NVIDIA graphics, VP9 HDR is playable and smooth using NVDEC, VA-API, and VDPAU. Likewise for AV01 HDR using NVDEC, but not VA-API and VDPAU.

**Comment by marioroy** [comment]
I'm new to the mpv player. Running `mpv url` wants a suitable YouTube downloader script.
```text
[ytdl_hook]  
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.
```
One can set `mpv` options in a configuration file `~/.config/mpv/mpv.conf`. For my use case, 10-bit (HDR) is accelerated with arguments `--hwdec=nvdec-copy` and `--vo=xv`. Also, specified the `yt-dlp` path and format.
```text
script-opts=ytdl_hook-ytdl_path=/home/mario/.local/bin/yt-dlp
ytdl-format=bestvideo[height<=?1440][fps<=?30][vcodec!=?vp9]+bestaudio/best
hwdec=nvdec-copy
vo=xv
```

**Comment by paulcarroty** [comment]
Moved to [Projects](https://github.com/clearfraction/distribution/projects).
