### ISSUE TITLE
mpv-cuda lacks Xv support

### ISSUE THREAD

**Issue by marioroy** [clearfraction/distribution#16]
The configure script enables Xv support automatically if the headers/libs exist on the machine, which was the case the other day.  So needs the `--enable-xv` option added explicitly to be sure included during the workflow automation.

Basically, `mpv --vo=xv` will fail without libXv support.

- [x] Update waf options - add `--enable-xv`
- [x] Update spec file - add libXv Requires, BuildRequires
- [x] Update bundles / configs / codecs-cuda - add `libXv-lib`

**Comment by marioroy** [comment]
@paulcarroty Is `Xv` support needed in codecs? Waf configure may have included support automatically on the dev box, but not the case during the workflow phase (lacking Xv headers / dev-libs).

**Comment by paulcarroty** [comment]
```
xv (X11 only)
Uses the XVideo extension to enable hardware-accelerated display. This is the most compatible VO on X, **but may be low-quality, and has issues with OSD and subtitle display.**

Note
**This driver is for compatibility with old systems.**
```

I don't think we need this, may be enabled on user request only.

**Comment by marioroy** [comment]
That is interesting as codecs and codecs-cuda are nearly identical with the excepting the latter adds nv-codec-headers and libvdpau. I installed CL 36840 on my Intel NUC followed by the 3rd-party codecs installation. xv is broken and verified using youtube-play-intel.  I changed `--vo=gpu` to `--vo=xv` in the script.

```bash
$ sudo swupd 3rd-party bundle-list
Installed bundles:
 - brave
 - codecs
 - os-core

Total: 3
```
```bash
$ ./youtube-play-intel https://youtu.be/Jz9TdfXlTgs
[vo] Video output xv not found!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```

**Comment by marioroy** [comment]
All is fine on the dev environment like you say. But not the case installing CL anew on an external drive and codecs.

**Comment by paulcarroty** [comment]
`xv` is legacy output, so don't care about it too much; also I'm on Wayland.

Tested `-vo=gpu -gpu-context=wayland` and `-vo=x11`, working fine.

**Comment by marioroy** [comment]
Thank you, `--vo=x11` is working for 10-bit HDR. Reverting the Xv change to codecs-cuda.

**Comment by marioroy** [comment]
Unfortunately, --vo=x11 has higher CPU usage versus --vo=xv.  So keeping the change. I can remove it later.
