### ISSUE TITLE
Defining globals vars in /etc/environment.d/10-cf.conf does not work

### ISSUE THREAD

**Issue by marioroy** [clearfraction/distribution#18]
The `/etc/environment.d` location may have worked some time ago, but not now.

I created locally `/etc/profile.d/10-cf.sh`. One must be careful defining variables in the `/etc/profile.d` location. Thus, it checks first for a CF path. BTW: Shouldn't `local` come first, matching the behavior in CL? For example, if codecs-cuda and codecs are both installed. Thus, local path must come first with respect to codecs-cuda. Ditto for the `/opt/3rd-party/bin` wrapper scripts.

/etc/profile.d/10-cf.sh

```bash
if [[ ! ${PATH} =~ "/opt/3rd-party/bundles/clearfraction/usr/bin" ]]; then
    PATH=${PATH}:/opt/3rd-party/bundles/clearfraction/usr/local/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/bin
fi

if [[ ! ${LD_LIBRARY_PATH} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64" ]]; then
    LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/local/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi

if [[ ! ${XDG_DATA_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share" ]]; then
    [[ ${XDG_DATA_DIRS:0:1} = ":" ]] && XDG_DATA_DIRS=${XDG_DATA_DIRS:1} # strip leading ":"
    XDG_DATA_DIRS=/opt/3rd-party/bundles/clearfraction/usr/local/share/:/opt/3rd-party/bundles/clearfraction/usr/share/:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}
fi

if [[ ! ${XDG_CONFIG_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share/xdg" ]]; then
    XDG_CONFIG_DIRS=/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg:${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}
fi

if [[ ! ${GST_PLUGIN_PATH_1_0} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0" ]]; then
    GST_PLUGIN_PATH_1_0=/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0:${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}
fi

if [[ ! ${FONTCONFIG_PATH} =~ "/usr/share/defaults/fonts" ]]; then
    FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}
fi
```

Thoughts

1. Appending to PATH isn't necessary as CL already has `/opt/3rd-party/bin` in the path. I do not understand why needing to add additional paths.
2. Local paths should come first in the `/opt/3rd-party/bin` wrapper scripts to be consistent with 10-cf.sh above?

**Comment by marioroy** [comment]
Created issue at Clear Linux as XDG_CONFIG_DIRS is overwritten in `/usr/share/defaults/etc/profile`.

https://github.com/clearlinux/distribution/issues/2708

**Comment by marioroy** [comment]
Created another issue at Clear Linux from seeing duplicate entries in `$XDG_DATA_DIRS`.

https://github.com/clearlinux/distribution/issues/2709

**Comment by paulcarroty** [comment]
In short: `/profile.d` is shell-only, no graphical environment support; GUI applications ignore it and fail to load their resources like themes/icons from `/opt`. 

> Appending to PATH isn't necessary as CL already has /opt/3rd-party/bin in the path. I do not understand why needing to add additional paths.

CF ignore `/opt/3rd-party/bin`, 'cause don't need yet another bash wrapper and higher app load latency.

**Comment by paulcarroty** [comment]
Update: `environment.d` works only with DE started by systemd services: GNOME, KDE, Sway(systemd session) etc. Xfce, i3wm, Enlightenment are off.

**Comment by marioroy** [comment]
Thank you for the explanation. I tried something.
1. Removed /etc/profile.d folder
2. Restored /etc/environment.d/10-cf.conf as per the README file
3. Removed ~/.local/share/applications/brave-browser.desktop
4. Rebooted the machine

Activities > Search > I enter Brave. Not found. The same for mpv, not found. The DE doesn't know about the CF desktop files.

```text
/opt/3rd-party/bundles/clearfraction/usr/local/share/applications/mpv.desktop
/opt/3rd-party/bundles/clearfraction/usr/share/applications/brave-browser.deskto
```

**Comment by marioroy** [comment]
Next, I tried the following:
1. Removed /etc/environment.d
2. Restored /etc/profile.d/10-cf.sh (as per above). There is an [issue](https://github.com/clearlinux/distribution/issues/2708) at CL, overwriting XDG_CONFIG_DIRS. Fortunately, this doesn't effect Activities > Search.
3. To validate searching /opt, I do not have ~/.local/share/applications/{mpv, brave-browser}.desktop

Activities > Search > mpv and Brave works. The DE knows about the CF desktop files.
```text
/opt/3rd-party/bundles/clearfraction/usr/local/share/applications/mpv.desktop
/opt/3rd-party/bundles/clearfraction/usr/share/applications/brave-browser.deskto
```

**Comment by paulcarroty** [comment]
> The DE doesn't know about the CF desktop files.

Check `XDG_DATA_DIRS`, DE should read it and load the resources from.

**Comment by marioroy** [comment]
I restored /etc/environment.d/10-cf.conf (removed /etc/profile.d/10-cf.sh) and rebooted the machine. It seems the DE doesn't know about CF paths. It cannot find { mpv, Brave } in Activities > Search field.

I'm testing from a clean CL installation and installed CF { codecs-cuda, brave } bundles.

**Comment by paulcarroty** [comment]
Please check Shotwell for the full picture, 'cause Brave come with his own wrapper and can manipulate with envs/paths.

**Comment by marioroy** [comment]
> Please check Shotwell for the full picture

Sure. The DE doesn't find mpv either in Activities > Search. Next tried Shotwell.

1. Removed /etc/profile.d/10-cf.sh
2. Restored /etc/environment.d/10-cf.conf
3. Rebooted the machine
4. Installed Shotwell via `sudo swupd 3rd-party bundle-add shotwell`

Activities > Search cannot find Brave, mpv, Shotwell

```text
/opt/3rd-party/bundles/clearfraction/usr/local/share/applications/mpv.desktop
/opt/3rd-party/bundles/clearfraction/usr/share/applications/brave-browser.desktop
/opt/3rd-party/bundles/clearfraction/usr/share/applications/org.gnome.Shotwell-Viewer.desktop
/opt/3rd-party/bundles/clearfraction/usr/share/applications/org.gnome.Shotwell.desktop
```
```bash
$ cat /etc/environment.d/10-cf.conf 
PATH=$PATH:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin
LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
XDG_DATA_DIRS=/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}
XDG_CONFIG_DIRS=/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg:${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}
FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}
GST_PLUGIN_PATH_1_0=/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0:${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}
```

**Comment by paulcarroty** [comment]
You don't need to reboot, re-login should be enough.

OK, `environment.d` is broken, report it to Clear. Let's migrate to `profile.d` & adjusted desktop entries.

**Comment by marioroy** [comment]
What creates the /opt/3rd-party/bin files? The local path should come first.

**Comment by paulcarroty** [comment]
Swupd trigger.

**Comment by marioroy** [comment]
https://github.com/clearlinux/distribution/issues/2710

**Comment by paulcarroty** [comment]
@marioroy tested your `profile.d` config, it brakes my Sway completely, but `TTY` session working fine. I think we should use both. Can you test them both in your GNOME?

**Comment by marioroy** [comment]
There is an [issue](https://github.com/clearlinux/distribution/issues/2708) request at CL for `XDG_CONFIG_DIRS` due to `/usr/share/defaults/etc/profile` overwriting it. Is that the reason why Sway is failing because XDG_CONFIG_DIRS lacks the /opt/3rd-party/... paths?

**Comment by marioroy** [comment]
If you hard code XDG_CONFIG_DIRS in /etc/profile.d/10-cf.sh with /opt/3rd-party paths, does it work?

**Comment by marioroy** [comment]
> Let's migrate to profile.d & adjusted desktop entries.

Can you explain the 2nd part of the sentence (adjusted desktop entries)?

**Comment by marioroy** [comment]
I installed CL sway, CF sway-extras, and CF waybar. However, I do not have the gears icon on my login screen after selecting my login name.

**Comment by paulcarroty** [comment]
> does Sway work?

Nope, Sway don't wanna know about `profile.d` at all: zero vars imported.

> adjusted desktop entries

Like [this](https://github.com/clearfraction/bundles/blob/master/build.sh#L68).

**Comment by paulcarroty** [comment]
Well, found the alternative: do the [import](https://github.com/swaywm/sway/wiki/Systemd-integration#loading-environment-variables-from-environmentd), bun in reverse. So we can sync the system environment variables with graphical.

**Comment by marioroy** [comment]
> Sway don't wanna know about profile.d at all

So, we need both? /etc/environment.d and /etc/profile.d?

Please when we edit the README file, have the local path come first in PATH and LD_LIBRARY_PATH. There is an [issue](https://github.com/clearlinux/distribution/issues/2710) ticket at CL for the swupd trigger to do the same for the /opt/3rd-party/bin wrapper scripts.

Just catching up :)

> found the alternative: do the [import](https://github.com/swaywm/sway/wiki/Systemd-integration#loading-environment-variables-from-environmentd), bun in reverse

Reading

**Comment by paulcarroty** [comment]
Congratulations with opening another rabbit hole!

Still not sure, will say more after testing.

**Comment by marioroy** [comment]
As you mentioned above, we need both environment.d (Sway) and profile.d (GNOME).

**Comment by marioroy** [comment]
Well, I'm hoping the CL dev team fixes issue [2708](https://github.com/clearlinux/distribution/issues/2708) so that XDG_CONFIG_DIRS var is not overwritten.
