### ISSUE TITLE
Download Error When trying to add repo

### ISSUE THREAD

**Issue by dedguy21** [clearfraction/distribution#19]
Update: This issue was resolved you can close issue. 

Think the issue was trying to add the repository on initial boot before inital swupd update.

I'm getting a Error: Curl - Download failed  when trying to add this repo per the instructions

**Comment by paulcarroty** [comment]
The repo was down 'cause of Heroku boot timeout issue, now fixed.

For the records: Heroku refuses to start images larger than 4.9 GB.
