### ISSUE TITLE
CPU ISA level is lower than required

### ISSUE THREAD

**Issue by x-sublime** [clearfraction/distribution#31]
Trying to open mpv, with release v39400, I get  this error " /opt/3rd-party/bundles/clearfraction/usr/lib64/libsharpyuv.so.0: CPU ISA level is lower than required".
  
CPU:
  Info: quad core model: Intel Core i5-3570T bits: 64 type: MCP
    smt: <unsupported> arch: Ivy Bridge rev: 9 cache: L1: 256 KiB L2: 1024 KiB
    L3: 6 MiB
  Speed (MHz): avg: 3100 high: 3300 min/max: 1600/3300 volts: 1.0 V
    ext-clock: 100 MHz cores: 1: 2900 2: 3300 3: 2900 4: 3300 bogomips: 18401
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
 

_____________________________________
 3rd-Party Repository: clearfraction
_____________________________________

Installed bundles:
 - codecs-cuda
 - os-core
 - yt-dlp

Total: 3

**Comment by paulcarroty** [comment]
The AVX2 migration happened: https://github.com/orgs/clearfraction/discussions/30

Workaround: extract [image-38990.tar.zst](https://github.com/clearfraction/bundles/releases/download/38990/image-38990.tar.zst) `/tmp/repo/image/38990/full/` to `/opt/3rd-party/bundles/clearfraction/`.

**Comment by x-sublime** [comment]
Thank you. Time to change my hardware, I think...

**Comment by paulcarroty** [comment]
https://v2download.clearfraction.cf is up, you can fix the `/opt/3rd-party/repo.ini` config to use it.
