### ISSUE TITLE
x86-64-v2 is broken

### ISSUE THREAD

**Issue by x-sublime** [clearfraction/distribution#32]
After enabling the above repository, trying to open mpv I get "/opt/3rd-party/bundles/clearfraction/usr/lib64/libx265.so.207: CPU ISA level is lower than required"

3rd-Party Repository: clearfraction
_____________________________________

Distribution:      Clear Linux OS
Installed version: 39450
Version URL:       https://v2download.clearfraction.cf/update
Content URL:       https://v2download.clearfraction.cf/update

Installed bundles:
 - codecs-cuda
 - os-core
 - yt-dlp

Total: 3

**Comment by paulcarroty** [comment]
Thx, found the [bug](https://github.com/clearfraction/mass-rebuild-v2/commit/f6226e0a92cabb159722ba37c5534e4ebf839286) and need to rebuild all. Wait for completed [CI jobs](https://github.com/clearfraction/mass-rebuild-v2/actions) and reinstall all bundles.

**Comment by x-sublime** [comment]
sudo swupd 3rd-party bundle-add codecs-cuda
Searching for bundle codecs-cuda in the 3rd-party repositories...
Bundle codecs-cuda found in 3rd-party repository clearfraction

Bundles added from a 3rd-party repository are forced to run with the --no-scripts flag for security reasons

Loading required manifests...

Validating 3rd-party bundle binaries...
 [100%]

No packs need to be downloaded
 [100%]

Validate downloaded files
 [100%]

Starting download of remaining update content. This may take a while (21 files)...
 [100%]

Error: Could not download some files from bundles, aborting bundle installation
Failed to install 1 of 1 bundles

bloom@hal9000~ $ sudo swupd 3rd-party info
_____________________________________
 3rd-Party Repository: clearfraction
_____________________________________

Distribution:      Clear Linux OS
Installed version: 39450
Version URL:       https://v2download.clearfraction.cf/update
Content URL:       https://v2download.clearfraction.cf/update


_____________________________________

**Comment by x-sublime** [comment]
Installed.

Now I have:
 mpv
/opt/3rd-party/bundles/clearfraction/usr/lib64/libSvtAv1Enc.so.1: CPU ISA level is lower than required

**Comment by paulcarroty** [comment]
Huh, this is Clear's library. Can you paste the hash? `sha512sum /opt/3rd-party/bundles/clearfraction/usr/lib64/libSvtAv1Enc.so.1`

**Comment by x-sublime** [comment]
The hash of said Clear's library:

sha512sum /opt/3rd-party/bundles/clearfraction/usr/lib64/libSvtAv1Enc.so.1
8afe90200c1642a0f2501535a8191548713417fcbdf71aba1f6e8bdacdbed87c4a4da96b2bbdf30729bcbb0ad3a89d0e6e34d9ffd60f7c9b277d583b060ac14d  /opt/3rd-party/bundles/clearfraction/usr/lib64/libSvtAv1Enc.so.1
 
Thanks very much for your help

**Comment by paulcarroty** [comment]
Waiting for the fix in https://github.com/clearlinux-pkgs/SVT-AV1.

**Comment by paulcarroty** [comment]
The update arrived, can you test it?

```
cd /tmp
curl -LO https://download.clearlinux.org/releases/39520/clear/x86_64/os/Packages/SVT-AV1-lib-1.6.0-22.x86_64.rpm
rpm2cpio SVT-AV1-lib-1.6.0-22.x86_64.rpm | cpio -idmv
sudo mv ./usr/lib64/libSvtAv1* /opt/3rd-party/bundles/clearfraction/usr/lib64/
ffmpeg -h
```

**Comment by x-sublime** [comment]
Installed and...

 ffmpeg -h
ffmpeg version 6.0-ea3d24b Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Clear Linux OS for Intel Architecture)
  configuration: --disable-static --extra-ldflags=-ldl --prefix=/usr/local-cuda --bindir=/usr/local-cuda/bin --datadir=/usr/local-cuda/share/ffmpeg --incdir=/usr/local-cuda/include/ffmpeg --libdir=/usr/local-cuda/lib64 --shlibdir=/usr/local-cuda/lib64 --enable-rdft --enable-pixelutils --extra-ldflags=-ldl --enable-vaapi --enable-bzlib --enable-libdrm --enable-fontconfig --enable-gcrypt --enable-gmp --enable-version3 --enable-gnutls --enable-ladspa --enable-libass --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-opengl --enable-libopus --enable-libpulse --enable-libsnappy --enable-libspeex --enable-libvorbis --enable-libv4l2 --enable-sdl2 --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-avfilter --enable-swscale --enable-postproc --enable-pthreads --enable-librtmp --enable-libmfx --disable-static --enable-shared --enable-gpl --disable-debug --disable-doc --enable-libfdk-aac --enable-nonfree --enable-libdav1d --enable-vulkan --enable-libglslang --enable-libsvtav1 --enable-nvdec --enable-nvenc --enable-vdpau --enable-libplacebo
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Hyper fast Audio and Video encoder

Thanks, you did great.
