### ISSUE TITLE
PKG_CONFIG_PATH mising?

### ISSUE THREAD

**Issue by Aqua1ung** [clearfraction/distribution#33]
In the ["How to enable the repository"](https://github.com/clearfraction/distribution#how-to-enable-the-repository) script I can't seem to find the line for setting the `PKG_CONFIG_PATH` variable. Is that required, or not? [This](https://github.com/clearfraction/docs/blob/main/README.md#how-to-build-software-using-clear-fraction-libraries-like-x264-x265-or-cuda) seems to be hinting that it might be, indeed, required.

**Comment by paulcarroty** [comment]
https://github.com/clearfraction/docs#how-to-build-software-using-clear-fraction-libraries-like-x264-x265-or-cuda

**Comment by paulcarroty** [comment]
It's required only for compilation.

**Comment by Aqua1ung** [comment]
Compilation of _what_? And, to the point, is `PKG_CONFIG_PATH` needed in order to obtain `libavcodec.a, libavutil.a, libavformat.a`, and  `libswscale.a`?

**Comment by paulcarroty** [comment]
Check the [FAQ](https://people.freedesktop.org/~dbn/pkg-config-guide.html#faq).
