### ISSUE TITLE
Adding CF repo renders computer unbootable

### ISSUE THREAD

**Issue by Aqua1ung** [clearfraction/distribution#34]
CL 39960: Adding CF repo according to [instructions here](https://github.com/clearfraction/distribution#how-to-enable-the-repository) renders my computer unbootable. Suggestions?

This is the script I use to enable the CF repo:
```
#!/bin/bash

# Run as root/sudo.
if [ ! $(id -u) == 0 ]
then
  echo "This script should be run as root! Exiting ..."
  exit
fi

swupd 3rd-party add clearfraction https://download.clearfraction.cf/update
mkdir -p /etc/environment.d /etc/profile.d
tee -a /etc/environment.d/10-cf.conf << 'EOF'
PATH=$PATH:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin
LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/
XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg
FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}
GST_PLUGIN_PATH_1_0=${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0
EOF

tee -a /etc/profile.d/10-cf.sh << 'EOF'
[[ ! ${PATH} =~ "/opt/3rd-party/bundles/clearfraction/bin" ]] && \
  PATH=$PATH:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin

[[ ! ${LD_LIBRARY_PATH} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64" ]] && \
  LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

[[ ! ${XDG_DATA_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share" ]] && \
  XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/

[[ ! ${XDG_CONFIG_DIRS} =~ "/opt/3rd-party/bundles/clearfraction/usr/share/xdg" ]] && \
  XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:-/usr/share/xdg:/etc/xdg}:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg

[[ ! ${FONTCONFIG_PATH} =~ "/usr/share/defaults/fonts" ]] && \
  FONTCONFIG_PATH=/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}

[[ ! ${GST_PLUGIN_PATH_1_0} =~ "/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0" ]] && \
  GST_PLUGIN_PATH_1_0=${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0
EOF

echo "Reboot!"
```

**Comment by paulcarroty** [comment]
Remove the `/etc/environment.d/10-cf.conf` and try again. If it will fail - paste here your `PATH` and `LD_LIBRARY_PATH` variables.

**Comment by Aqua1ung** [comment]
> Remove the `/etc/environment.d/10-cf.conf` and try again. If it will fail - paste here your `PATH` and `LD_LIBRARY_PATH` variables.

How can I remove it if I cannot boot? And I should try again ... what? Running the script, or rebooting? (I very much appreciate your hard work, but please bear with me, as I am having trouble understanding your instructions.)

**Comment by paulcarroty** [comment]
> How can I remove it if I cannot boot?

- Boot from livecd
- remove that file
- try again using the README command

**Comment by Aqua1ung** [comment]
@paulcarroty, thank you! Looks to me that the `10-cf.conf` file does _not_ need to exist in order to have access to the ClearFraction repo (hence that seems to be just an intermediary step): Is that so? Currently I do _not_ have a `10-cf.conf` file, but can boot just fine and all variables seem to have the right values.

Anyway, here's what I did:
1. restored my system from a CloneZilla backup;
2. ran CF script as usual;
3. before doing a reboot I deleted the `10-cf.conf` file;
4. rebooted: reboot proceeded just fine;
5. checked variables, and all seem to have the right values.
Granted, all this could be achieved by simply commenting out the part in the CF script that creates the `10-cf.conf` file, hence I am back to asking what role that file has. Is it essential?

**Comment by paulcarroty** [comment]
Docs: https://www.freedesktop.org/software/systemd/man/environment.d.html

GUI apps mostly don't care about shell env variables, so we have to use both  configs - `/etc/environment` and  `/etc/profile.d/`.

**Comment by K1ngfish3r** [comment]
Alternatively, if anyone else stumbles upon this whilst reaching a white error screen, you can use `Ctrl + Alt + F5` to reach a tty
Login and `rm /etc/environment.d/10-cf.conf`

**Comment by paulcarroty** [comment]
Safe debugging method: add the repo using the README commands, paste the `systemctl --user show-environment` output and remove `/etc/environment.d/10-cf.conf`.

**Comment by paulcarroty** [comment]
Tested with CF 40040 - no issues.

**Comment by K1ngfish3r** [comment]
with CL 40050 and CF 40040 still unbootable
see output of `systemctl --user show-environment` below
```bash
HOME=/home/i
LANG=C.UTF-8
LOGNAME=i
PATH=/usr/local/bin:/usr/bin:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin
SHELL=/bin/bash
SYSTEMD_EXEC_PID=1000
USER=i
XDG_DATA_DIRS=/home/i/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/
XDG_RUNTIME_DIR=/run/user/1000
LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64
XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg
FONTCONFIG_PATH=/usr/share/defaults/fonts
GST_PLUGIN_PATH_1_0=/usr/lib64/gstreamer-1.0:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
```

**Comment by paulcarroty** [comment]
I tested it again on 40050 live image and found the reason:

```
clrlinux@clr-live~ $ systemctl --user show-environment
PATH=/usr/bin/haswell:/usr/local/bin:/usr/bin:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin:/opt/3rd-party/bin

LD_LIBRARY_PATH=$'/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}'

FONTCONFIG_PATH=$'/usr/share/defaults/fonts${FONTCONFIG_PATH:+:$FONTCONFIG_PATH}'

GST_PLUGIN_PATH_1_0=$'${GST_PLUGIN_PATH_1_0:-/usr/lib64/gstreamer-1.0}:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0'
```
LD_LIBRARY_PATH *is broken* together with FONTCONFIG_PATH and GST_PLUGIN_PATH_1_0.
Can you reproduce this?


P.S. CFLAGS too: `CFLAGS=$'-g -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -Wformat -Wformat-security -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z,now -Wl,-z,relro -fno-semantic-interposition -ffat-lto-objects -fno-trapping-math -Wl,-sort-common -Wl,>`

P.S.S. It's only on GNOME, my Sway envs are OK.

**Comment by nsorlien** [comment]
From my testing, `XDG_DATA_DIRS` and `XDG_CONFIG_DIRS` in `/etc/environment.d/10-cf.conf` are the cause. 

With either value present, one of my machines (i7-12700H) hangs to a non-blinking cursor on boot, and I need to boot with `nomodeset` to fix it. The other (i5-1140G7) hits the white GDM greeter crash screen, and I can switch to a virtual console to fix it. The Clear Linux installations should be otherwise identical between them.

**Comment by paulcarroty** [comment]
Let's test this version of `/etc/environment.d/10-cf.conf`:

```
PATH=/usr/bin/haswell:/usr/bin:/usr/local/bin:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:/opt/3rd-party/bundles/clearfraction/usr/local/bin
LD_LIBRARY_PATH=/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:/opt/3rd-party/bundles/clearfraction/usr/local/lib64
XDG_DATA_DIRS=/usr/share:/usr/local/share:/opt/3rd-party/bundles/clearfraction/usr/share:/opt/3rd-party/bundles/clearfraction/usr/local/share
XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg:/opt/3rd-party/bundles/clearfraction/usr/share/xdg:/opt/3rd-party/bundles/clearfraction/etc/xdg
FONTCONFIG_PATH=/usr/share/defaults/fonts
GST_PLUGIN_PATH_1_0=/usr/lib64/gstreamer-1.0:/opt/3rd-party/bundles/clearfraction/usr/lib64/gstreamer-1.0
```

It works fine on 40050 image, but needs more testers.

**Comment by Aqua1ung** [comment]
@paulcarroty: tested on 40060, looks like it's working fine. More testers please!

**Comment by nsorlien** [comment]
Works for me as well!

I had to manually add `/home/user/.local/share/flatpak/exports/share` to `XDG_DATA_DIRS` to get gnome software apps to show up.

**Comment by K1ngfish3r** [comment]
Tested on a clean install of CL 40060 for my new 2tb. can confirm new paths work.

**Comment by K1ngfish3r** [comment]
doing `echo $XDG_DATA_DIRS` shows the correct path however `XDG_DATA_DIRS` has a tendency to add quotes around itself, causing flatpaks to not appear again
```
i@clr~ $ systemctl --user show-environment
XDG_DATA_DIRS=$'/usr/share:/usr/local/share:/opt/3rd-party/bundles/clearfraction/usr/share:/opt/3rd-party/bundles/clearfraction/usr/local/share/home/$USER/.local/share/flatpak/exports/share'
```
I've tried a few shortcuts such as `~` and `$HOME` as well as `${USER}` and double quotes around the whole thing, but they dont seem to work. Only changing $USER to [actual user name] seems to work

**Comment by paulcarroty** [comment]
Yeah, added the note - `tee` will write actual `$USER`.
