### ISSUE TITLE
pkg-config paths are broken

### ISSUE THREAD

**Issue by K1ngfish3r** [clearfraction/distribution#35]
issue: using the command `pkg-config --list-all | grep fdk` provides no response
bundles added: `codecs` and `devpkg-codecs`
current CL version as of writing: 40010

More info: Whilst following the [Readme](https://github.com/clearfraction/docs/blob/main/README.md#how-to-build-software-using-clear-fraction-libraries-like-x264-x265-or-cuda), `Now check if the library is available` ends in failure as libfdk is unable to be found

using `swupd 3rd-party bundle-info devpkg-codecs --files` shows that the files are supposed to be in the `/usr/` folder however upon searching the files are in `/opt/3rd-party/bundles/clearfraction/usr/`.  The `export $PKG_CONFIG_PATH` command in the [Readme](https://github.com/clearfraction/docs/blob/main/README.md#how-to-build-software-using-clear-fraction-libraries-like-x264-x265-or-cuda) only points towards the `/include/` folders. pkg-config is unable to find libfdk with this configuration.

If I change the `$PKG_CONFIG_PATH` to `/opt/3rd-party/bundles/clearfraction/usr/lib64/pkgconfig` instead, it appears in `pkg-config`, however the .pc files direct towards files which are in `/usr/` instead of `/opt/3rd-party/bundles/clearfraction/usr/` which results in builds failing cause the necessary files were unable to be found.

The only other thing I can think of right now, is to manually change all the .pc files inside the pkgconfig folder in the clearfraction bundle location to point towards the 3rd-party location, which I'm pretty sure is not right. Please halp

**Comment by paulcarroty** [comment]
> shows that the files are supposed to be in the /usr/ folder however upon searching the files are in /opt/3rd-party/bundles/clearfraction/usr/.

This is designed by Clear Linux, the third-party lives in /opt.

**Comment by paulcarroty** [comment]
> however the .pc files direct towards files which are in /usr/ instead 

You found the bug, the paths should be fixed. I'll try to add this in new release.

Another way is build stuff like CF and Clear Linux does: [RPM repository](https://github.com/clearfraction/bundles/releases/download/39400/packages-39400.tar) and rpmbuild tool.

If you're building something open source - welcome to contribute it to the project.
