### ISSUE TITLE
keyd failed to set effective group?

### ISSUE THREAD

**Issue by K1ngfish3r** [clearfraction/distribution#36]
CL 40060 and CF 40040, running `sudo keyd` leads to the following
```
sudo keyd
WARNING: failed to set effective group to "keyd" (make sure the group exists)
opendir: No such file or directory
```
UPDATE: after adding default.conf it works but i still get the error
```
sudo keyd
WARNING: failed to set effective group to "keyd" (make sure the group exists)
CONFIG: parsing /etc/keyd/default.conf
Starting keyd v2.4.3 ()
DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
DEVICE: match    045e:0800  /etc/keyd/default.conf	(Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control)
DEVICE: ignoring 045e:0800  (Microsoft Microsoft® Nano Transceiver v2.0 Consumer Control)
DEVICE: ignoring 045e:0800  (Microsoft Microsoft® Nano Transceiver v2.0 Mouse)
DEVICE: match    045e:0800  /etc/keyd/default.conf	(Microsoft Microsoft® Nano Transceiver v2.0)
DEVICE: match    1b1c:1b74  /etc/keyd/default.conf	(Corsair CORSAIR GLAIVE RGB PRO Gaming Mouse Keyboard)
DEVICE: ignoring 1b1c:1b74  (Corsair CORSAIR GLAIVE RGB PRO Gaming Mouse Consumer Control)
DEVICE: ignoring 1b1c:1b74  (Corsair CORSAIR GLAIVE RGB PRO Gaming Mouse)
```

This error did not come up in the last CF release (39400)
UPDATE 2: Updated to 40060, no changes so far
TL:DR solution. `groupadd keyd`

**Comment by paulcarroty** [comment]
> WARNING: failed to set effective group to "keyd"

From README: Add yourself to the keyd group: `usermod -aG keyd <user>`

The keyd package was updated in July, so this is probably not related to current CF release. Also you need the [symlink](https://github.com/clearfraction/distribution/wiki/Dbus-and-systemd-services) and probably `python-xlib`.

**Comment by K1ngfish3r** [comment]
> From README: Add yourself to the keyd group: `usermod -aG keyd <user>`
```i@clr~ $ usermod -aG keyd i
usermod: group 'keyd' does not exist```

> Also you need the [symlink](https://github.com/clearfraction/distribution/wiki/Dbus-and-systemd-services)
to `sudo systemctl enable keyd`, this works `sudo ln -s /opt/3rd-party/bundles/clearfraction/usr/lib/systemd/user/keyd.service /usr/lib/systemd/system/keyd.service`
idk why symlinking to `/usr/lib/systemd/usr/keyd.service` doesnt work

`keyd.service` also needs to point to `/opt/3rd-party/bin/keyd` instead of `/usr/bin/keyd`
```
i@clr~ $ sudo systemctl status keyd
× keyd.service - key remapping daemon
     Loaded: loaded (/etc/systemd/system/keyd.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Sun 2023-10-08 16:42:00 +08; 1min 0s ago
   Duration: 807us
    Process: 48799 ExecStart=/usr/bin/keyd (code=exited, status=203/EXEC)
   Main PID: 48799 (code=exited, status=203/EXEC)

Oct 08 16:42:00 clr systemd[1]: Started keyd.service.
Oct 08 16:42:00 clr (keyd)[48799]: keyd.service: Failed to locate executable /usr/bin/keyd: No such file or directory
Oct 08 16:42:00 clr (keyd)[48799]: keyd.service: Failed at step EXEC spawning /usr/bin/keyd: No such file or directory
Oct 08 16:42:00 clr systemd[1]: keyd.service: Main process exited, code=exited, status=203/EXEC
Oct 08 16:42:00 clr systemd[1]: keyd.service: Failed with result 'exit-code'.
```

**Comment by paulcarroty** [comment]
```
usermod: group 'keyd' does not exist
```

Well, `groupadd keyd` ftw.

I never used this software before, it was the package request. Thx for the testing, @K1ngfish3r .
