### ISSUE TITLE
VSCodium missing title bar

### ISSUE THREAD

**Issue by K1ngfish3r** [clearfraction/distribution#38]
Problem: Missing top bar as seen in photo
https://cdn.discordapp.com/attachments/1082816074585739375/1166604836180074496/image.png?ex=654b186b&is=6538a36b&hm=2b872714f133afb0bf3b44670c57e8051ab19757ef526eda6c85f7a307d3a096&

Expected: Not missing

Steps to replicate
1. Open VSCodium from Application Menu
2. It went missing

CL 40130
CF 40060

**Comment by paulcarroty** [comment]
It is Wayland or X11?

**Comment by K1ngfish3r** [comment]
Wayland

**Comment by paulcarroty** [comment]
Got the same issue, it's probably related to https://github.com/microsoft/vscode/issues/184124.

Workaround: extract newer or older VSCodium rpm to `/opt/3rd-party/bundles/clearfraction/usr/share/codium/`, don't forget to clean the dir before extraction.
