### ISSUE TITLE
Missing fmt dependency

### ISSUE THREAD

**Issue by dasouza** [clearfraction/distribution#39]
I'm getting this error with CL 40130 when trying to run waybar:

```
/opt/3rd-party/bundles/clearfraction/usr/bin/waybar: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory
```

Installing `devpkg-fmt` from the Clear repository fixes the issue.

**Comment by paulcarroty** [comment]
Ah, thought about removing it - too many problems with build dependencies.
