### ISSUE TITLE
Error: bundle <package name> was not found in any 3rd-party repository

### ISSUE THREAD

**Issue by FXTe1Y** [clearfraction/distribution#45]
Issue with clearlinux version 41120

Any app whats listed on github trying to install on clearlinux returns error message
`swupd 3rd-party bundle-add brave
Searching for bundle brave in the 3rd-party repositories...
Error: bundle brave was not found in any 3rd-party repository
`
`sudo swupd 3rd-party bundle-add codecs
Searching for bundle codecs in the 3rd-party repositories...
Error: bundle codecs was not found in any 3rd-party repository`

Possible issue could be when visiting website https://clearfraction.vercel.app/update i'm unable to see any current version

**Comment by paulcarroty** [comment]
Format bump happened: https://download.clearlinux.org/update/version/format35/

This can be fixed by pointing swupd to the right package format:

```
swupd 3rd-party bundle-add brave -F 34
```

**Comment by oQ-Qo** [comment]
same happen to me, I tried copy paste all code for adding repository then add bundles with -F 34 but still failed. It Turns out that I actually failed at adding repository, but I am not notice it because I run all codes together at same time. so adding repository with -F 34  SOLVED IT
