### ISSUE TITLE
Waydroid

### ISSUE THREAD

**Issue by paulcarroty** [clearfraction/distribution#47]
Attempt to bring Waydroid to Clear Linux, based on @K1ngfish3r [experience](https://community.clearlinux.org/t/waydroid-on-clear-linux/7470/8).

The repos:
- [waydroid](https://github.com/clearfraction/waydroid)
- [lxc](https://github.com/clearfraction/lxc)
- [libgbinder](https://github.com/clearfraction/libgbinder)
- [libglibutil](https://github.com/clearfraction/libglibutil)
- [gbinder-python](https://github.com/clearfraction/gbinder-python)
- [pyclip](https://github.com/clearfraction/pyclip)

TODO:
- [x]  create the above RPM packages
- [x] single Waydroid [tarball](https://github.com/clearfraction/waydroid/actions) with all deps for comfortable QA
- [x] symlink install/uninstall script for systemd/dbus services

Test bundle available [here](https://github.com/clearfraction/waydroid/actions).

**Comment by K1ngfish3r** [comment]
How do i make the programs install into `/opt`?
I made this [.spec](https://gist.github.com/K1ngfish3r/6a4f26aa19214c12e3cbc4ceef85db5e)

**Comment by paulcarroty** [comment]
Great!
About `/opt` - you don't need to, swupd take care.

**Comment by paulcarroty** [comment]
Can you push it to https://github.com/clearfraction/lxc ?

**Comment by K1ngfish3r** [comment]
I made a pr for lxc https://github.com/clearfraction/lxc/pull/1
Specs for the other packages
[libglibutil.spec](https://gist.github.com/K1ngfish3r/60c0cb57be4679eefb1d8f5ec0f7263f)
[libgbinder.spec](https://gist.github.com/K1ngfish3r/65951755ffa2836e3840ebcdf1284038)
[gbinder-python.spec](https://gist.github.com/K1ngfish3r/27ee5c052fa2960df6db4afc3f242fe1)
[pyclip.spec](https://gist.github.com/K1ngfish3r/a15be6aa033e651b311364314428d479)
[waydroid.spec](https://gist.github.com/K1ngfish3r/b27f597912e2a70cc97600af7acb1477)

**Comment by paulcarroty** [comment]
@K1ngfish3r you're monster!
I'm going to create the repos and get CI working.
Feel free to push or make the PRs.

**Comment by paulcarroty** [comment]
There are two types of CI:
- [build-core.yml](https://github.com/clearfraction/zed/raw/main/.github/workflows/build.yml) without dependencies
- [build.yml](https://github.com/clearfraction/ffmpeg/blob/master/.github/workflows/build.yml) with dependencies

**Comment by K1ngfish3r** [comment]
added workflows
[libglibutil](https://github.com/clearfraction/libglibutil/pull/2)
[libgbinder](https://github.com/clearfraction/libgbinder/pull/2)
[gbinder-python](https://github.com/clearfraction/gbinder-python/pull/2)
[pyclip](https://github.com/clearfraction/pyclip/pull/2)
[waydroid](https://github.com/clearfraction/waydroid/pull/2)

**Comment by paulcarroty** [comment]
CI passed. Next stage:

- [ ] single Waydroid tarball with all deps for comfortable QA
- [ ] symlink install/uninstall script for systemd/dbus services

**Comment by paulcarroty** [comment]
I think it's better to keep RPM packages untouched for ability to test them inside   `/usr/' prefix and apply modifications to `/waydroid` and `/bundles`.

**Comment by K1ngfish3r** [comment]
Here is a prerequisites script
```
#!/bin/bash

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Install required bundles
sudo swupd bundle-add kvm-host containers-basic

# Create directory if it doesn't exist and add required kernel parameters
sudo mkdir -p /etc/kernel/cmdline.d
sudo sh -c 'echo "systemd.unified_cgroup_hierarchy=1" >> /etc/kernel/cmdline.d/lxc.conf'
sudo sh -c 'echo "psi=1" >> /etc/kernel/cmdline.d/lxc.conf'

# Update bootloader configuration
sudo clr-boot-manager update

# Enable libvirtd and additional services
sudo systemctl enable libvirtd libvirt-guests virtlxcd virtstoraged virtnetworkd virtnodedevd

echo "Setup complete."
```

**Comment by paulcarroty** [comment]
I suggest to make PR to https://github.com/clearfraction/bundles with file cf-waydroid-installer.
You can also integrate it directly to waydroid RPM. So it's up to you.

We also need to add symlinks to this script.

**Comment by K1ngfish3r** [comment]
Need script to reboot first before continuing with install so I make two script? Or should I append the symlink changes to the script as well?

**Comment by paulcarroty** [comment]
We need 2 scripts: `cf-waydroid-preinstall.sh` and `cf-waydroid-uninstall.sh`.

**Comment by paulcarroty** [comment]
Waydroid bundle is [here](https://github.com/clearfraction/waydroid/actions/runs/9601241405).

It can be extracted to `/opt/3rd-party/bundles/clearfraction` for testing.

**Comment by paulcarroty** [comment]
And maybe it will be better to ask user to reboot manually.

**Comment by paulcarroty** [comment]
Symlinks:

```
/usr/lib/systemd/system/{lxc-monitord.service,lxc-net.service,lxc.service,lxc@.service,waydroid-container.service}

/usr/lib/tmpfiles.d/lxc.conf

/usr/libexec/lxc/hooks/unmount-namespace

/usr/libexec/lxc/{lxc-apparmor-load,lxc-containers,lxc-monitord,lxc-net,lxc-user-nic}

/usr/sbin/init.lxc # not sure CF has this in PATH

/usr/share/dbus-1/system-services/id.waydro.Container.service

/usr/share/dbus-1/system.d/id.waydro.Container.conf

/usr/share/polkit-1/actions

/usr/share/lxc
```

**Comment by K1ngfish3r** [comment]
`/usr/bin/waydroid` is missing in the bundle

**Comment by K1ngfish3r** [comment]
![image](https://github.com/clearfraction/distribution/assets/26593485/e9a4544f-3193-4160-a276-b19ab823ccf3)
/usr/bin/waydroid seems to be a symlink to /usr/lib/waydroid/waydroid.py

**Comment by paulcarroty** [comment]
Fixed - zip removed the symlink.

**Comment by K1ngfish3r** [comment]
```
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/etc/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Fri 2024-06-21 19:16:54 +08; 4s ago
    Process: 24646 ExecStart=/opt/3rd-party/bundles/clearfraction/usr/bin/waydroid -w container start (code=exited, status=1/FAILURE)
   Main PID: 24646 (code=exited, status=1/FAILURE)
        CPU: 49ms

Jun 21 19:16:54 clr waydroid[24646]:   File "/opt/3rd-party/bundles/clearfraction/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
Jun 21 19:16:54 clr waydroid[24646]:     import tools.helpers.props
Jun 21 19:16:54 clr waydroid[24646]:   File "/opt/3rd-party/bundles/clearfraction/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
Jun 21 19:16:54 clr waydroid[24646]:     from tools.interfaces import IPlatform
Jun 21 19:16:54 clr waydroid[24646]:   File "/opt/3rd-party/bundles/clearfraction/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
Jun 21 19:16:54 clr waydroid[24646]:     import gbinder
Jun 21 19:16:54 clr waydroid[24646]: ModuleNotFoundError: No module named 'gbinder'
Jun 21 19:16:54 clr systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 19:16:54 clr systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
Jun 21 19:16:54 clr systemd[1]: Failed to start waydroid-container.service.
```
This is usually worked around by adding the bundle `python-data-science`
So now the question is, what does the bundle do?

**Comment by paulcarroty** [comment]
Did you create all symlinks? Is the lxc working without issues?

**Comment by K1ngfish3r** [comment]
created an environment file with env > /etc/waydroid environment
then added that file to the service
```
[Unit]
Description=Waydroid Container

[Service]
BusName=id.waydro.Container
EnvironmentFile="/etc/waydroid/environment"
ExecStart=/opt/3rd-party/bundles/clearfraction/usr/bin/waydroid -w container start

[Install]
WantedBy=multi-user.target
```
then no errors
```
i@clr~ $ sudo systemctl status waydroid-container.service 
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/etc/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-06-21 22:33:45 +08; 8s ago
   Main PID: 56415 (python3)
      Tasks: 2 (limit: 18813)
     Memory: 18.1M (peak: 19.3M)
        CPU: 84ms
     CGroup: /system.slice/waydroid-container.service
             └─56415 python3 /opt/3rd-party/bundles/clearfraction/usr/bin/waydroid -w container start

Jun 21 22:33:45 clr systemd[1]: Starting waydroid-container.service...
Jun 21 22:33:45 clr systemd[1]: Started waydroid-container.service.
```
however trying to run `waydroid session start`
```
i@clr~ $ waydroid session start
[23:08:24] OSError: container failed to start
```
probably really close to fixing it

**Comment by paulcarroty** [comment]
LXC merged, waiting for CI finish.
P.S. You have the rw access and can do it too.

**Comment by paulcarroty** [comment]
Also maybe it's worth to change `/usr/lib64/lxc/rootfs` to something more suitable like `/var/lxc`?

**Comment by K1ngfish3r** [comment]
> LXC merged, waiting for CI finish. P.S. You have the rw access and can do it too.

LOL, anyways
![image](https://github.com/clearfraction/distribution/assets/26593485/8478d34f-a2ce-49c2-8662-2d9404c5a960)


Mission success
> Also maybe it's worth to change `/usr/lib64/lxc/rootfs` to something more suitable like `/var/lxc`?
you try first

**Comment by paulcarroty** [comment]
Great job!
The default path, according to docs, is `/var/lib/lxc/<container>/rootfs`. Can you check where's your container rootfs?

Which symlinks we need to add into install script?

**Comment by paulcarroty** [comment]
Also hardcoding python version `/etc/waydroid/environment` is bad thing, 'cause it will stop working soon.

**Comment by K1ngfish3r** [comment]
> Also hardcoding python version `/etc/waydroid/environment` is bad thing, 'cause it will stop working soon.

> Do you have `PYTHONPATH` env var with `gbinder` module location? Edit - negative, 'cause I was forced to remove it due to some issues.

I tried to find a way around it without making it global. EnvironmentFile was a shot, any ideas?

> Can you check where's your container rootfs?

`/var/lib/waydroid/rootfs`

> Which symlinks we need to add into install script?

I used all the ones you outlined in the previous comment, didn't add any extra.

**Comment by paulcarroty** [comment]
> EnvironmentFile was a shot

Good shot. Code LLM suggest you can use bash inside it like 

```
Environment="VARIABLE_NAME=$(bash -c 'echo $SOME_VAR')"
```

> to keep updating clearfraction.patch

Nooo, let's automate it.

**Comment by K1ngfish3r** [comment]
Issue I had previously with setting manual PATH variable
```bash
i@clr~ $ sudo systemctl status waydroid-container.service 
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/etc/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Sat 2024-06-22 17:49:42 +08; 9s ago
    Process: 24940 ExecStart=/opt/3rd-party/bundles/clearfraction/usr/bin/waydroid -w container start (code=exited, status=127)
   Main PID: 24940 (code=exited, status=127)
        CPU: 2ms

Jun 22 17:49:42 clr systemd[1]: Starting waydroid-container.service...
Jun 22 17:49:42 clr waydroid[24940]: /usr/bin/env: ‘python3’: No such file or directory
```
Here is current waydroid-container.service file
```bash
[Unit]
Description=Waydroid Container

[Service]
BusName=id.waydro.Container
Environment="PYTHONPATH=$(bash -c 'echo /opt/3rd-party/bundles/clearfraction/usr/lib/python$(echo /usr/lib/python* | tr -d '/usr/lib/python')')"
Environment="LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/lib64"
Environment="_=/usr/bin/env"
Environment="PATH=$(bash -c 'echo $PATH')"
ExecStart=/opt/3rd-party/bundles/clearfraction/usr/bin/waydroid -w container start

[Install]
WantedBy=multi-user.target
```

**Comment by K1ngfish3r** [comment]
> Another idea: https://unix.stackexchange.com/a/758402

Got it working https://github.com/clearfraction/waydroid/commit/5e69ae77391ab6236edba12847d399fc44dc6c1f

**Comment by paulcarroty** [comment]
Nice job. I think you should clean CF patches and submit these packages to Clear.

**Comment by K1ngfish3r** [comment]
Waydroid actually needs kernel parameters to work properly so I'm not sure that's feasible. Do any clear packages append kernel params when they're being added?

**Comment by paulcarroty** [comment]
> Do any clear packages append kernel params when they're being added?

No idea, but user can do it manually. So submit them all, don't be shy.

Waydroid bundle will be in next release, soon after Linux 6.10.

**Comment by K1ngfish3r** [comment]
I tested it the latest artifact on a new bare metal install
Turns out, PYTHONPATH needs to be globally available

**Comment by paulcarroty** [comment]
Merged, thx. If Clear team refuse to add your other packages, you can always add them to CF too.

Think to change PYTHONPATH globally to `/opt/3rd-party/bundles/clearfraction/usr/lib/python`, but not sure about time saving.

**Comment by paulcarroty** [comment]
@K1ngfish3r can you enable strip to all?

**Comment by K1ngfish3r** [comment]
Stripping enabled by default in autospec https://github.com/clearfraction/waydroid/blob/8db719626aa0dbe9dfb916c7ba94a3c62e81e01f/options.conf#L48

**Comment by paulcarroty** [comment]
https://github.com/clearfraction/lxc/blob/main/lxc.spec#L38 ?

**Comment by paulcarroty** [comment]
@K1ngfish3r new release arrived, please test.

**Comment by K1ngfish3r** [comment]
> @K1ngfish3r new release arrived, please test.

![image](https://github.com/user-attachments/assets/ab08a220-d5c8-4a81-b38e-d938f5bed012)
works after exporting `PYTHONPATH=/opt/3rd-party/bundles/clearfraction/usr/lib/python3.12/site-packages/`

**Comment by paulcarroty** [comment]
[Fixed](https://github.com/clearfraction/bundles/commit/e4e793aa8c31cf60313d3e305f77ed73a89e64d8).

**Comment by K1ngfish3r** [comment]
> [Fixed](https://github.com/clearfraction/bundles/commit/e4e793aa8c31cf60313d3e305f77ed73a89e64d8).

https://github.com/clearfraction/bundles/pull/7
Deleting it after the script is done doesnt work

**Comment by paulcarroty** [comment]
That will be broken on Python 3.13+.

**Comment by paulcarroty** [comment]
Fixed, try again.

**Comment by K1ngfish3r** [comment]
This works, but as you said, this going to break on Python update, and i cant think of anyway to dynamically setup environment variables globally on boot.

**Comment by paulcarroty** [comment]
Investigated a bit and found that `sudo` removes all env vars after exit.
We need to rewrite `cf-waydroid-init.sh` without sudo.

**Comment by paulcarroty** [comment]
Test the latest `cf-waydroid-init.sh`.

**Comment by K1ngfish3r** [comment]
added in CL 42200: https://github.com/clearlinux/distribution/issues/3154

**Comment by paulcarroty** [comment]
Great news, will move the CF build to archive.

**Comment by K1ngfish3r** [comment]
LXC is provided. Tested on a fresh CL 42200 install
