### ISSUE TITLE
Flatpak references wiped out

### ISSUE THREAD

**Issue by Aqua1ung** [clearfraction/distribution#49]
It appears that installing the ClearFraction repo and/or ClearFraction ffmpeg has wiped out all the references to my flatpak apps. The apps are still installed, but all the icons and links to the apps are gone.

For example, I had Chrome _flatpak_ designated as default  Web app, and now it's FireFox. And no, there is no way in the Default Apps widget to switch to Chrome. Same for VLC: I had VLC as default for music and video, but now it has defaulted to the default Gnome app "Videos."

![Screenshot from 2024-08-24 13-58-35](https://github.com/user-attachments/assets/d825ea3d-555b-4479-b8e6-939494c8bd77)

How can this be fixed? I tried `sudo flatpak repair` to no avail.

**Comment by paulcarroty** [comment]
Can you post the output of `systemctl --user show-environment | grep XDG_DATA_DIRS` ?

**Comment by Aqua1ung** [comment]
> Can you post the output of `systemctl --user show-environment | grep XDG_DATA_DIRS` ?

```dad@DadsGram~ $ systemctl --user show-environment | grep XDG_DATA_DIRS
XDG_DATA_DIRS=/usr/share:/usr/local/share:/opt/3rd-party/bundles/clearfraction/usr/share:/opt/3rd-party/bundles/clearfraction/usr/local/share:/home/dad/.local/share/flatpak/exports/share:/home/dad/.local/share/flatpak/exports/share
```

**Comment by paulcarroty** [comment]
Is this the `/home/dad/.local/share/flatpak/exports/share` valid with desktop entries inside?

**Comment by paulcarroty** [comment]
Thanks, please test the fixed version to make sure it's working now.

**Comment by Aqua1ung** [comment]
> Thanks, please test the fixed version to make sure it's working now.

Done. Things are back to normal. Thanks!

**Comment by Aqua1ung** [comment]
@paulcarroty, here's one more question for you (and thank you for your CF work!): it appears that CL _does_ come with an older version of the ffmpeg libraries, located in `/usr/lib64`. The CF ffmpeg libraries are stored, as you very well know, in `/opt/3rd-party/bundles/clearfraction/usr/lib64`. The `LD_LIBRARY_PATH` is set to _both_ of these, yet the "active" library is the CF one:
```
dad@DadsGram/usr/lib64 $ which ffmpeg
/opt/3rd-party/bundles/clearfraction/usr/bin/ffmpeg
```
How does the system know that the CF library is the one it should use (the "active" one)?
