### ISSUE TITLE
Package Request: Zen Browser

### ISSUE THREAD

**Issue by K1ngfish3r** [clearfraction/distribution#53]
https://copr-dist-git.fedorainfracloud.org/cgit/sneexy/zen-browser/zen-browser-avx2.git/tree/

I would like more packages starting with Z in my third-party repo please

**Comment by paulcarroty** [comment]
Well, looks like another one experimental Firefox fork. Not quite interesting, but let it be.

> more packages starting with Z

why?

**Comment by paulcarroty** [comment]
Access [granted](https://github.com/clearfraction/zen-browser/).
