### ISSUE TITLE
Brave install issue

### ISSUE THREAD

**Issue by da0ist** [clearfraction/distribution#6]
Warning: The 3rd-party bundle you are about to install contains files with dangerous permission
Do you want to continue? (y/N): y

Installing files...
 [100%]

Warning: post-update helper scripts skipped due to --no-scripts argument

Exporting 3rd-party bundle binaries...
Warning: File /usr/bin/brave-browser-stable does not have 'execute' permission so it won't be exported
 [100%]

Successfully installed 1 bundle

**Comment by paulcarroty** [comment]
Guess it happens 'cause flatpak package overwrite $XDG_DATA_DIRS and you'll never see Brave launcher. 

Fix: 

```
echo "XDG_DATA_DIRS=/opt/3rd-party/bundles/clearfraction/usr/share/:/opt/3rd-party/bundles/clearfraction/usr/local/share/:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}" >> /usr/share/gdm/env.d/flatpak.env
```

**Comment by paulcarroty** [comment]
https://github.com/clearfraction/distribution/issues/7#issuecomment-1043396578
