### ISSUE TITLE
Brave installation failed

### ISSUE THREAD

**Issue by Chrysipus** [clearfraction/distribution#7]
![image](https://user-images.githubusercontent.com/99507331/153658748-8c4e7c02-ef7c-4e55-9e8c-2e1409f7c481.png)

The Brave browser is installed... But not really. 
Any easy fix?

**Comment by paulcarroty** [comment]
Sure. You can ignore the swupd warning about default `chrome-sandbox` SUID permission. I guess you need the GDM fix from [README](https://github.com/clearfraction/distribution#how-to-enable-the-repository). Is this GNOME, KDE, X, Wayland?

**Comment by paulcarroty** [comment]
Fix: 

```
sed -i 's|--enable-features=UseOzonePlatform --ozone-platform=wayland|--ozone-platform-hint=auto|g' /opt/3rd-party/bundles/clearfraction/usr/share/applications/brave-browser.desktop 
```
Will be included in next release.
