### ISSUE TITLE
How to add BSPWM, Picom, Polybar, and Btop++

### ISSUE THREAD

**Issue by dedguy21** [clearfraction/distribution#9]
Love what you're doing here. Tried using Clear and the mixing tool a couple of years ago and was completely lost. 

I still lost just not as much. Anyway I was wondering how to use the tool to add some of my favorites window Manager to my Clear box. 

Or it might be something you can add to your repo since you know what you're doing :)

**Comment by paulcarroty** [comment]
[BSPWM progress](https://github.com/clearfraction/distribution/projects/1#card-79293954)

**Comment by paulcarroty** [comment]
Btop++ will be available in next release, BSPWM already added to Clear Linux repository, Picom & Polybar - unknown 'cause Sway in priority now.
